actions:
  - https://pay.weixin.qq.com/docs/merchant/apis/jsapi-payment/direct-jsons/jsapi-prepay.html
  - https://pay.weixin.qq.com/docs/merchant/apis/jsapi-payment/query-by-wx-trade-no.html

notices:
  - https://pay.weixin.qq.com/docs/merchant/apis/jsapi-payment/payment-notice.html
